import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex  justify-between py-2 h-[5vh] ">
            <Link href="/" className="flex-1  text-center">
              Home
            </Link>
           <div className="flex justify-around  flex-1 ">
           <Link href="/posts">
              Posts
            </Link>
            <Link href="/users">
              Users
            </Link>
            <Link href="/albums">
              Photos
            </Link>
            <Link href="/login">
              Log - in
            </Link>

           </div>
        </div>
        {children}
        
        </body>
    </html>
  );
}
